# BSSCI mioty Add-on Build Konfiguration
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
  armhf: "ghcr.io/home-assistant/armhf-base:3.19"
  i386: "ghcr.io/home-assistant/i386-base:3.19"
labels:
  org.opencontainers.image.title: "BSSCI mioty Sensor Manager"
  org.opencontainers.image.description: "Home Assistant Add-on für mioty IoT Sensoren über BSSCI Service Center"
  org.opencontainers.image.source: "https://github.com/your-repo/bssci-mioty-addon"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"