# Minimale Home Assistant Konfiguration für BSSCI mioty Integration

# Basis-Setup ohne problematische Komponenten
homeassistant:
  name: "BSSCI mioty Test"
  country: DE
  latitude: 52.5200
  longitude: 13.4050
  elevation: 0
  unit_system: metric
  time_zone: "Europe/Berlin"

# HTTP Server
http:
  server_port: 5000
  server_host: 0.0.0.0
  use_x_forwarded_for: true
  trusted_proxies:
    - 127.0.0.1
    - ::1

# Frontend
frontend:

# API für externe Zugriffe
api:

# Logging
logger:
  default: info
  logs:
    custom_components.bssci_mioty: debug

# Einfacher Recorder ohne Probleme
recorder:
  db_url: sqlite:///ha_test.db
  purge_keep_days: 3

# Basis Sensor für Tests
sensor:
  - platform: time_date
    display_options:
      - 'time'