[project]
name = "repl-nix-workspace"
version = "0.2.1"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "paho-mqtt>=1.6.0",
    "voluptuous>=0.15.2",
    "pycryptodomex>=3.20",
]
