add_sensor:
  name: Sensor hinzufügen
  description: Fügt einen neuen mioty Sensor hinzu und konfiguriert ihn
  fields:
    sensor_eui:
      name: Sensor EUI
      description: Die eindeutige Kennung des Sensors (EUI-64)
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{16}$"
    network_key:
      name: Netzwerk-Schlüssel
      description: 32-stelliger Hex-Netzwerk-Schlüssel
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{32}$"
    short_addr:
      name: Kurze Adresse
      description: 4-stellige Hex-Kurz-Adresse
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{4}$"
    bidirectional:
      name: Bidirektional
      description: Aktiviert bidirektionale Kommunikation
      required: false
      default: false
      selector:
        boolean:

configure_sensor:
  name: Sensor konfigurieren
  description: Konfiguriert einen existierenden mioty Sensor
  fields:
    sensor_eui:
      name: Sensor EUI
      description: Die eindeutige Kennung des Sensors (EUI-64)
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{16}$"
    network_key:
      name: Netzwerk-Schlüssel
      description: 32-stelliger Hex-Netzwerk-Schlüssel
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{32}$"
    short_addr:
      name: Kurze Adresse
      description: 4-stellige Hex-Kurz-Adresse
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{4}$"
    bidirectional:
      name: Bidirektional
      description: Aktiviert bidirektionale Kommunikation
      required: false
      default: false
      selector:
        boolean:

remove_sensor:
  name: Sensor entfernen
  description: Entfernt einen mioty Sensor aus Home Assistant
  fields:
    sensor_eui:
      name: Sensor EUI
      description: Die eindeutige Kennung des Sensors (EUI-64)
      required: true
      selector:
        text:
          pattern: "^[0-9a-fA-F]{16}$"
